//! Build-time fixups.
//!
//! On Windows we compile the app icon into the executable.
//!
//! On Android we package the media-notification controller. `dx build` / `dx serve`
//! regenerate the Gradle project from a template embedded in the `dx` binary every
//! run, with no way to inject our media classes (`MediaSessionHelper` / `MusicService`
//! / `MediaReceiver`), the custom `MainActivity`, or the `<service>`/`<receiver>`
//! manifest entries the notification controls need.
//!
//! Wry exposes `WRY_ANDROID_KOTLIN_FILES_OUT_DIR` so a build script can drop Kotlin
//! into the generated source tree. dx sets it in the cargo environment, the manifest
//! is written before cargo runs (and Gradle assembles after), so this script runs at
//! exactly the right point to copy our Kotlin and patch the manifest. Because it's
//! part of the cargo build it fires for `dx build` and `dx serve` alike — no
//! post-build script required.

use std::fs;
use std::path::{Path, PathBuf};

/// Permissions the notification + foreground playback service require.
const PERMISSIONS: &[&str] = &[
    "android.permission.INTERNET",
    "android.permission.POST_NOTIFICATIONS",
    "android.permission.FOREGROUND_SERVICE",
    "android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK",
    "android.permission.WAKE_LOCK",
    "android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS",
    "android.permission.READ_EXTERNAL_STORAGE",
    "android.permission.WRITE_EXTERNAL_STORAGE",
    "android.permission.READ_MEDIA_AUDIO",
    "android.permission.READ_MEDIA_IMAGES",
];

/// R8 keep rules. In release (`dx bundle`) minification is on and only keeps
/// `dev.dioxus.main.*`; our media classes are reached purely through JNI
/// (`MediaSessionHelper` is loaded by name, `MediaReceiver.nativeOnAction` is a
/// native method), so without these R8 strips or renames them and the controls
/// silently break in release. The release build.gradle globs `**/*.pro`, so
/// dropping this file into the source tree is enough to wire it in.
const KEEP_RULES: &str = r#"# AUTO-GENERATED by kopuz/build.rs — keep JNI-reached classes from R8.
-keep class moe.kopuz.kopuz.** { *; }
-keepclassmembers class moe.kopuz.kopuz.** { *; }
-keep class dev.dioxus.main.MainActivity { *; }
-keep class org.rustls.platformverifier.** { *; }
-keepclassmembers class org.rustls.platformverifier.** { *; }
"#;

/// Replaces the config dx generates, which permits cleartext to `127.0.0.1` only —
/// a LAN Jellyfin or Navidrome is almost always plain `http://`, and Android 9+
/// blocks that, so every such server looked unreachable.
const NETWORK_SECURITY_CONFIG: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<!-- AUTO-GENERATED by kopuz/build.rs -->
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>
"#;

/// Media control icons, as vector drawables written into the generated project —
/// the framework ships `ic_media_play`/`_next`/`_previous` and nothing else. Glyphs
/// are the Material Symbols paths (Apache-2.0); `dot` marks the active state the
/// way YouTube Music does, since the system tints every control the same colour and
/// the drawing is the only thing left to carry state.
struct MediaIcon {
    name: &'static str,
    glyph: &'static str,
    dot: bool,
}

const SHUFFLE: &str = "M10.59,9.17L5.41,4 4,5.41l5.17,5.17 1.42,-1.41zM14.5,4l2.04,2.04L4,18.59 5.41,20 17.96,7.46 20,9.5L20,4h-5.5zM14.83,13.41l-1.41,1.41 3.13,3.13L14.5,20L20,20v-5.5l-2.04,2.04 -3.13,-3.13z";
const REPEAT: &str = "M7,7h10v3l4,-4 -4,-4v3L5,5v6h2L7,7zM17,17L7,17v-3l-4,4 4,4v-3h12v-6h-2v4z";
const REPEAT_ONE: &str = "M7,7h10v3l4,-4 -4,-4v3L5,5v6h2L7,7zM17,17L7,17v-3l-4,4 4,4v-3h12v-6h-2v4zM13,15L13,9h-1l-2,1v1h1.5v4L13,15z";

const MEDIA_ICONS: &[MediaIcon] = &[
    MediaIcon {
        name: "kopuz_ic_shuffle",
        glyph: SHUFFLE,
        dot: false,
    },
    MediaIcon {
        name: "kopuz_ic_shuffle_on",
        glyph: SHUFFLE,
        dot: true,
    },
    MediaIcon {
        name: "kopuz_ic_repeat",
        glyph: REPEAT,
        dot: false,
    },
    MediaIcon {
        name: "kopuz_ic_repeat_on",
        glyph: REPEAT,
        dot: true,
    },
    MediaIcon {
        name: "kopuz_ic_repeat_one_on",
        glyph: REPEAT_ONE,
        dot: true,
    },
];

/// `<service>` + `<receiver>` injected just inside `</application>`.
const INSIDE_APPLICATION: &str = r#"        <service
            android:name="moe.kopuz.kopuz.MusicService"
            android:foregroundServiceType="mediaPlayback"
            android:stopWithTask="false"
            android:exported="false" />
        <receiver
            android:name="moe.kopuz.kopuz.MediaReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="moe.kopuz.kopuz.ACTION_MEDIA" />
            </intent-filter>
        </receiver>
        <activity
            android:name="moe.kopuz.kopuz.LoginActivity"
            android:exported="false" />
"#;

fn warn(msg: &str) {
    println!("cargo:warning={msg}");
}

/// Chromium freezes a hidden page's JS exactly 60s after the activity leaves
/// the foreground, and dioxus parks every task behind the render
/// acknowledgement that frozen page can no longer send — the media
/// notification goes dead and the queue stops advancing while audio plays on.
/// Freezing is keyed purely off page visibility (a held Web Lock does not
/// exempt it), so the generated `RustWebView` is patched to report its window
/// as always visible: the page never counts as hidden, never freezes, and
/// background playback control keeps working.
///
/// A missing anchor is a hard build failure on purpose: shipping without the
/// patch silently re-breaks background playback, so a wry template change has
/// to surface here, not on users' phones. dx rewrites the file every build, so
/// the call site re-runs whenever it changes.
fn patch_rust_webview(path: &Path) {
    let content = fs::read_to_string(path).unwrap_or_else(|e| {
        panic!(
            "cannot read {} — dx should have generated it before cargo ran: {e}",
            path.display()
        )
    });
    const MARKER: &str = "// kopuz: page-freeze patch";
    if content.contains(MARKER) {
        return;
    }
    const ANCHOR: &str = "): WebView(context) {";
    const OVERRIDES: &str = r#"): WebView(context) {
    // kopuz: page-freeze patch
    override fun onWindowVisibilityChanged(visibility: Int) {
        super.onWindowVisibilityChanged(android.view.View.VISIBLE)
    }

    override fun onVisibilityAggregated(isVisible: Boolean) {
        super.onVisibilityAggregated(true)
    }
"#;
    assert!(
        content.contains(ANCHOR),
        "RustWebView.kt anchor `{ANCHOR}` not found ({}); the wry template \
         changed — update patch_rust_webview to match it",
        path.display()
    );
    let patched = content.replacen(ANCHOR, OVERRIDES, 1);
    if let Err(e) = fs::write(path, patched) {
        panic!("cannot write {}: {e}", path.display());
    }
}

/// Inline the vendored woff2 fonts into the bundled font CSS as base64 `data:`
/// URIs, writing the result to `OUT_DIR`. `main.rs` pulls these in via
/// `include_str!(concat!(env!("OUT_DIR"), "/..."))`, so the fonts are compiled
/// straight into the binary — styling works under a bare `cargo run` on any OS
/// (no CDN, no asset collection, no path resolution). The committed CSS keeps
/// readable `url(fonts/NAME.woff2)` refs; the woff2 live in `assets/fonts/`.
/// Regenerate the inputs with `nu scripts/vendor-fonts.nu`.
fn embed_fonts(crate_dir: &Path) {
    let assets = crate_dir.join("assets");
    let fonts = assets.join("fonts");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));

    for css_name in ["fontawesome.css", "jetbrains-mono.css", "main.css"] {
        let src = assets.join(css_name);
        println!("cargo:rerun-if-changed={}", src.display());
        let css = match fs::read_to_string(&src) {
            Ok(c) => c,
            Err(e) => {
                warn(&format!("cannot read {}: {e}", src.display()));
                continue;
            }
        };
        let baked = bake_font_css(&css, &fonts);
        let dst = out_dir.join(css_name);
        if let Err(e) = fs::write(&dst, baked) {
            warn(&format!("cannot write {}: {e}", dst.display()));
        }
    }
}

/// Emit the favicon as a `data:` URI string to `OUT_DIR/favicon.uri`, so it's
/// compiled into the binary and renders under a bare `cargo run` (an `asset!()`
/// favicon needs `dx` to collect it). `main.rs` reads it via `include_str!`.
fn embed_favicon(crate_dir: &Path) {
    use base64::Engine;
    let src = crate_dir.join("assets").join("favicon.ico");
    println!("cargo:rerun-if-changed={}", src.display());
    let bytes = match fs::read(&src) {
        Ok(b) => b,
        Err(e) => {
            warn(&format!("cannot read {}: {e}", src.display()));
            return;
        }
    };
    let b64 = base64::engine::general_purpose::STANDARD.encode(&bytes);
    let uri = format!("data:image/x-icon;base64,{b64}");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));
    let dst = out_dir.join("favicon.uri");
    if let Err(e) = fs::write(&dst, uri) {
        warn(&format!("cannot write {}: {e}", dst.display()));
    }
}

/// Replace every `url(fonts/NAME.EXT)` with an inline `data:` URI read from
/// `fonts/NAME.EXT`. Panics on a missing/unterminated ref so a broken vendor
/// step fails the build loudly instead of silently shipping unstyled icons.
fn bake_font_css(css: &str, fonts: &Path) -> String {
    use base64::Engine;
    const PREFIX: &str = "url(fonts/";

    let mut out = String::with_capacity(css.len());
    let mut rest = css;
    while let Some(idx) = rest.find(PREFIX) {
        out.push_str(&rest[..idx]);
        let after = &rest[idx + PREFIX.len()..];
        let end = after
            .find(')')
            .unwrap_or_else(|| panic!("unterminated `{PREFIX}` in font CSS"));
        let file = &after[..end];
        let path = fonts.join(file);
        println!("cargo:rerun-if-changed={}", path.display());
        let bytes =
            fs::read(&path).unwrap_or_else(|e| panic!("cannot read font {}: {e}", path.display()));
        let mime = match Path::new(file).extension().and_then(|e| e.to_str()) {
            Some("woff2") => "font/woff2",
            Some("woff") => "font/woff",
            Some("otf") => "font/otf",
            Some("ttf") => "font/ttf",
            _ => "application/octet-stream",
        };
        let b64 = base64::engine::general_purpose::STANDARD.encode(&bytes);
        out.push_str("url(data:");
        out.push_str(mime);
        out.push_str(";base64,");
        out.push_str(&b64);
        out.push(')');
        rest = &after[end + 1..];
    }
    out.push_str(rest);
    out
}

fn main() {
    let crate_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let asset_crate_dir = std::env::var_os("KOPUZ_ASSET_FILE")
        .map(PathBuf::from)
        .and_then(|path| path.parent()?.parent().map(Path::to_path_buf))
        .unwrap_or_else(|| crate_dir.clone());
    embed_fonts(&asset_crate_dir);
    embed_favicon(&asset_crate_dir);

    #[cfg(target_os = "windows")]
    {
        let mut res = winres::WindowsResource::new();
        res.set_icon("assets/app.ico");
        res.compile().expect("failed to compile Windows resources");
    }

    println!("cargo:rerun-if-env-changed=WRY_ANDROID_KOTLIN_FILES_OUT_DIR");

    // Only do anything android-specific on Android builds; on desktop the env var
    // is absent and we return after the Windows resource step above.
    let out_dir = match std::env::var("WRY_ANDROID_KOTLIN_FILES_OUT_DIR") {
        Ok(d) => PathBuf::from(d),
        Err(_) => return,
    };

    // android-src lives at the repo root (crates/kopuz/../../android-src).
    let android_src = crate_dir.join("..").join("..").join("android-src");
    // Re-run when files are added/removed under android-src. Note: a directory's mtime
    // does NOT change when an existing file inside it is edited, so this alone misses
    // edits — copy_file/copy_kt_dir additionally emit rerun-if-changed per source file.
    println!("cargo:rerun-if-changed={}", android_src.display());

    // out_dir = <project>/app/src/main/kotlin/dev/dioxus/main
    //   ancestors: [.../dev/dioxus/main, .../dev/dioxus, .../dev, .../kotlin]
    let kotlin_root = match out_dir.ancestors().nth(3) {
        Some(p) => p.to_path_buf(),
        None => {
            warn(&format!(
                "unexpected WRY kotlin out dir: {}",
                out_dir.display()
            ));
            return;
        }
    };
    let main_dir = match kotlin_root.parent() {
        Some(p) => p.to_path_buf(),
        None => return,
    };
    let manifest = main_dir.join("AndroidManifest.xml");

    // Older (manual) builds copied the helper classes under the java/ source root.
    // If those linger alongside our kotlin/ copies, both source sets compile the same
    // classes and Kotlin fails with "Redeclaration". Remove the stale java/ copies.
    let stale_java = main_dir.join("java/moe/kopuz/kopuz");
    if stale_java.exists() {
        let _ = fs::remove_dir_all(&stale_java);
    }

    // 1. Copy the media helper classes (package moe.kopuz.kopuz). Clear the dest
    //    first so a renamed/removed source class can't leave an orphan .kt behind.
    let helper_src = android_src.join("java/moe/kopuz/kopuz");
    let helper_dst = kotlin_root.join("moe/kopuz/kopuz");
    let _ = fs::remove_dir_all(&helper_dst);
    copy_kt_dir(&helper_src, &helper_dst);

    let verifier_src = android_src.join("java/org/rustls/platformverifier");
    let verifier_dst = kotlin_root.join("org/rustls/platformverifier");
    let _ = fs::remove_dir_all(&verifier_dst);
    copy_kt_dir(&verifier_src, &verifier_dst);

    // 2. Override the generated MainActivity (package dev.dioxus.main) so it wires
    //    up MediaSessionHelper and requests the notification permission at startup.
    let main_activity_src = android_src.join("kotlin/dev/dioxus/main/MainActivity.kt");
    let main_activity_dst = out_dir.join("MainActivity.kt");
    copy_file(&main_activity_src, &main_activity_dst);

    let rust_webview = out_dir.join("RustWebView.kt");
    println!("cargo:rerun-if-changed={}", rust_webview.display());
    patch_rust_webview(&rust_webview);

    // 3. Patch the freshly-generated manifest with permissions + service + receiver.
    //    dx rewrites this file every build, so re-run whenever it changes.
    if manifest.exists() {
        println!("cargo:rerun-if-changed={}", manifest.display());
        patch_manifest(&manifest);
    } else {
        warn(&format!(
            "AndroidManifest.xml not found at {}",
            manifest.display()
        ));
    }

    // 4. Drop R8 keep rules so release (`dx bundle`) minification doesn't strip the
    //    JNI-reached Kotlin. The release build.gradle globs **/*.pro under the module.
    copy_str(&main_dir.join("kopuz-keep.pro"), KEEP_RULES);

    // 5. Generate launcher icons from our logo. dx only ships its default icon, so
    //    build them here.
    generate_launcher_icons(&main_dir.join("res"));
    write_media_icons(&main_dir.join("res"));
    write_notification_icon(&asset_crate_dir, &main_dir.join("res"));

    // 5b. Replace dx's network security config; the manifest already points at it.
    copy_str(
        &main_dir.join("res/xml/network_security_config.xml"),
        NETWORK_SECURITY_CONFIG,
    );

    // 6. dx templates `versionCode = 1` into the module's Gradle script and never
    //    moves it, so every release would look like the same build to Android and
    //    refuse to install over its predecessor. Derive it from the crate version.
    if let Some(app_dir) = main_dir.parent().and_then(Path::parent) {
        patch_version_code(&app_dir.join("build.gradle.kts"));
        patch_sdk_levels(&app_dir.join("build.gradle.kts"));
        let _ = fs::remove_dir_all(app_dir.join("libs"));
    }
}

/// Status-bar icon for the media notification, generated from the brand
/// symbol SVG. Android renders small icons as pure alpha masks, so only the
/// symbol's light "details" layer (the instrument) is emitted, all white —
/// the dark disc behind it would flatten the icon into a featureless circle.
/// The strings and pegs survive as the negative space between those paths.
/// The viewport is padded to a square so the 24dp icon keeps the symbol's
/// aspect ratio.
fn write_notification_icon(asset_dir: &Path, res: &Path) {
    let svg_path = asset_dir.join("assets/logo-symbol.svg");
    let svg = match fs::read_to_string(&svg_path) {
        Ok(s) => s,
        Err(e) => {
            warn(&format!("cannot read {}: {e}", svg_path.display()));
            return;
        }
    };
    println!("cargo:rerun-if-changed={}", svg_path.display());

    let viewport = svg
        .split_once("viewBox=\"")
        .and_then(|(_, rest)| rest.split_once('"'))
        .and_then(|(vb, _)| {
            let mut dims = vb.split_whitespace().skip(2).map(str::parse::<f32>);
            match (dims.next(), dims.next()) {
                (Some(Ok(w)), Some(Ok(h))) => Some((w, h)),
                _ => None,
            }
        });
    let Some((width, height)) = viewport else {
        warn("logo-symbol.svg has no viewBox; notification icon skipped");
        return;
    };
    let side = width.max(height);
    let (tx, ty) = ((side - width) / 2.0, (side - height) / 2.0);

    fn attr<'a>(tag: &'a str, name: &str) -> Option<&'a str> {
        let (_, rest) = tag.split_once(&format!("{name}=\""))?;
        rest.split_once('"').map(|(value, _)| value)
    }

    fn is_light(fill: &str) -> bool {
        let hex = fill.strip_prefix('#').unwrap_or(fill);
        if hex.len() != 6 {
            return false;
        }
        let Ok(rgb) = u32::from_str_radix(hex, 16) else {
            return false;
        };
        let (r, g, b) = (rgb >> 16 & 0xff, rgb >> 8 & 0xff, rgb & 0xff);
        (r + g + b) / 3 > 128
    }

    let mut paths = String::new();
    let mut rest = svg.as_str();
    while let Some(start) = rest.find("<path ") {
        let after = &rest[start..];
        let Some(end) = after.find('>') else { break };
        let tag = &after[..end];
        if let Some(d) = attr(tag, "d")
            && attr(tag, "fill").is_some_and(is_light)
        {
            paths.push_str(&format!(
                "        <path android:fillColor=\"#FFFFFFFF\" android:pathData=\"{d}\" />\n"
            ));
        }
        rest = &after[end + 1..];
    }
    if paths.is_empty() {
        warn("logo-symbol.svg has no light <path>; notification icon skipped");
        return;
    }

    for (suffix, _) in [
        ("mdpi", 0),
        ("hdpi", 0),
        ("xhdpi", 0),
        ("xxhdpi", 0),
        ("xxxhdpi", 0),
    ] {
        let _ = fs::remove_file(res.join(format!("drawable-{suffix}/kopuz_ic_notification.png")));
    }

    let xml = format!(
        r#"<?xml version="1.0" encoding="utf-8"?>
<!-- AUTO-GENERATED by kopuz/build.rs from assets/logo-symbol.svg -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="{side}"
    android:viewportHeight="{side}">
    <group android:translateX="{tx}" android:translateY="{ty}">
{paths}    </group>
</vector>
"#
    );
    copy_str(&res.join("drawable/kopuz_ic_notification.xml"), &xml);
}

/// Android needs a single monotonically increasing integer. `major.minor.patch`
/// packs into one as long as minor and patch stay under 100 — 0.14.0 becomes
/// 1400, 1.0.0 becomes 10000.
///
/// Past 99 the fields would carry into each other and two different releases
/// could claim the same code (0.14.100 and 0.15.0 both give 1500), so the build
/// stops instead: a silently duplicated code makes an update uninstallable.
fn android_version_code() -> u32 {
    let version = env!("CARGO_PKG_VERSION");
    let mut parts = version
        .split(['.', '-'])
        .map(|p| p.parse::<u32>().unwrap_or(0));
    let major = parts.next().unwrap_or(0);
    let minor = parts.next().unwrap_or(0);
    let patch = parts.next().unwrap_or(0);
    assert!(
        minor < 100 && patch < 100,
        "crate version {version} cannot be packed into an android versionCode: \
         minor and patch have to stay below 100"
    );
    major * 10_000 + minor * 100 + patch
}

fn write_media_icons(res: &Path) {
    for icon in MEDIA_ICONS {
        // The dot needs room under the glyph, so an active icon shrinks it slightly
        // rather than letting the two collide.
        let body = if icon.dot {
            format!(
                r##"    <group android:scaleX="0.85" android:scaleY="0.85" android:pivotX="12" android:pivotY="10">
        <path android:fillColor="#FFFFFFFF" android:pathData="{}" />
    </group>
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="M10.4,21.5a1.6,1.6 0 1,0 3.2,0a1.6,1.6 0 1,0 -3.2,0z" />"##,
                icon.glyph
            )
        } else {
            format!(
                r##"    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="{}" />"##,
                icon.glyph
            )
        };
        let xml = format!(
            r#"<?xml version="1.0" encoding="utf-8"?>
<!-- AUTO-GENERATED by kopuz/build.rs -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
{body}
</vector>
"#
        );
        copy_str(
            &res.join("drawable").join(format!("{}.xml", icon.name)),
            &xml,
        );
    }
}

/// Google Play requires new apps and updates to target the previous year's API
/// level (36 as of the Aug 2026 deadline); dx templates 34 and never moves it.
fn patch_sdk_levels(gradle: &Path) {
    let Ok(content) = fs::read_to_string(gradle) else {
        warn(&format!("cannot read {}", gradle.display()));
        return;
    };
    let patched = content
        .replace("compileSdk = 34", "compileSdk = 36")
        .replace("targetSdk = 34", "targetSdk = 36");
    if patched != content
        && let Err(e) = fs::write(gradle, patched)
    {
        warn(&format!("cannot write {}: {e}", gradle.display()));
    }
}

/// Rewrite `versionCode = <n>` in the generated module Gradle script. Idempotent:
/// re-running with the same crate version is a no-op.
fn patch_version_code(gradle: &Path) {
    let Ok(content) = fs::read_to_string(gradle) else {
        warn(&format!("cannot read {}", gradle.display()));
        return;
    };
    let Some(start) = content.find("versionCode = ") else {
        warn(&format!("no versionCode in {}", gradle.display()));
        return;
    };
    let digits = start + "versionCode = ".len();
    let end = digits
        + content[digits..]
            .find(|c: char| !c.is_ascii_digit())
            .unwrap_or(0);
    let wanted = android_version_code().to_string();
    if content[digits..end] == wanted {
        return;
    }
    let patched = format!("{}{wanted}{}", &content[..digits], &content[end..]);
    if let Err(e) = fs::write(gradle, patched) {
        warn(&format!("cannot write {}: {e}", gradle.display()));
    }
}

/// Resize kopuz/assets/logo.png into the Android launcher mipmaps, replacing dx's
/// default icon. Writes raster PNGs and removes dx's webp + the adaptive-icon XML so the
/// logo is used directly (avoids "duplicate resources" and adaptive overriding the raster).
fn generate_launcher_icons(res: &Path) {
    if !res.is_dir() {
        return;
    }
    let logo = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("assets/logo.png");
    println!("cargo:rerun-if-changed={}", logo.display());
    let img = match image::open(&logo) {
        Ok(i) => i,
        Err(e) => {
            warn(&format!("cannot open logo {}: {e}", logo.display()));
            return;
        }
    };

    // (density dir suffix, px size)
    let densities = [
        ("mdpi", 48u32),
        ("hdpi", 72),
        ("xhdpi", 96),
        ("xxhdpi", 144),
        ("xxxhdpi", 192),
    ];
    for (suffix, size) in densities {
        let dir = res.join(format!("mipmap-{suffix}"));
        if !dir.is_dir() {
            continue;
        }
        // Remove dx's webp variants so they don't collide with our PNG.
        let _ = fs::remove_file(dir.join("ic_launcher.webp"));
        let _ = fs::remove_file(dir.join("ic_launcher_round.webp"));
        let resized = img.resize_exact(size, size, image::imageops::FilterType::Lanczos3);
        if let Err(e) = resized.save(dir.join("ic_launcher.png")) {
            warn(&format!("cannot write {} icon: {e}", suffix));
        }
    }

    // Drop the adaptive-icon descriptors so API 26+ uses our raster icon directly
    // instead of dx's default vector foreground/background.
    let anydpi = res.join("mipmap-anydpi-v26");
    let _ = fs::remove_file(anydpi.join("ic_launcher.xml"));
    let _ = fs::remove_file(anydpi.join("ic_launcher_round.xml"));
}

fn copy_str(dst: &Path, contents: &str) {
    if let Some(parent) = dst.parent() {
        let _ = fs::create_dir_all(parent);
    }
    if let Err(e) = fs::write(dst, contents) {
        warn(&format!("cannot write {}: {e}", dst.display()));
    }
}

fn copy_kt_dir(src: &Path, dst: &Path) {
    let entries = match fs::read_dir(src) {
        Ok(e) => e,
        Err(e) => {
            warn(&format!("cannot read {}: {e}", src.display()));
            return;
        }
    };
    if let Err(e) = fs::create_dir_all(dst) {
        warn(&format!("cannot create {}: {e}", dst.display()));
        return;
    }
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("kt")
            && let Some(name) = path.file_name()
        {
            copy_file(&path, &dst.join(name));
        }
    }
}

fn copy_file(src: &Path, dst: &Path) {
    // Per-file so editing this exact source re-triggers the build script.
    println!("cargo:rerun-if-changed={}", src.display());
    if let Some(parent) = dst.parent() {
        let _ = fs::create_dir_all(parent);
    }
    if let Err(e) = fs::copy(src, dst) {
        warn(&format!(
            "cannot copy {} -> {}: {e}",
            src.display(),
            dst.display()
        ));
    }
}

/// Mirror of android-src/patch_manifest.py's manifest logic, in Rust so it runs as
/// part of the cargo build. Idempotent: each insertion is guarded by a presence check.
fn patch_manifest(path: &Path) {
    let mut content = match fs::read_to_string(path) {
        Ok(c) => c,
        Err(e) => {
            warn(&format!("cannot read {}: {e}", path.display()));
            return;
        }
    };
    let original = content.clone();

    for perm in PERMISSIONS {
        let marker = format!("android:name=\"{perm}\"");
        if !content.contains(&marker) {
            content = content.replacen(
                "    <application ",
                &format!("    <uses-permission android:name=\"{perm}\" />\n    <application "),
                1,
            );
        }
    }

    if !content.contains("android:requestLegacyExternalStorage=\"true\"") {
        content = content.replacen(
            "    <application ",
            "    <application android:requestLegacyExternalStorage=\"true\" ",
            1,
        );
    }

    // singleTask: the foreground service + wake lock keep our process alive in the
    // background, so relaunching from the launcher would otherwise spin up a *second*
    // MainActivity in the live process and call WryActivity_create twice — which tao
    // can't survive and aborts with SIGABRT. singleTask reuses the existing instance
    // (onNewIntent instead of a fresh onCreate) so native init only ever runs once.
    if !content.contains("android:launchMode=") {
        content = content.replacen(
            "<activity ",
            "<activity android:launchMode=\"singleTask\" ",
            1,
        );
    }

    if !content.contains("MusicService") {
        content = content.replacen(
            "    </application>",
            &format!("{INSIDE_APPLICATION}    </application>"),
            1,
        );
    }

    if content != original
        && let Err(e) = fs::write(path, &content)
    {
        warn(&format!("cannot write {}: {e}", path.display()));
    }
}
