//! File-based settings store (issue #530): a `settings.toml` the app reads and
//! writes, layered with `settings.d/*.toml` drop-ins and `KOPUZ_CONFIG_*`
//! environment overrides so a Nix/hjem-managed (immutable) config works
//! without the app ever writing to it.
//!
//! TOML is the on-disk format because this file is meant to be hand-written and
//! generated by Nix (`pkgs.formats.toml`); the values themselves still travel as
//! `serde_json::Value`, which is what `AppConfig` round-trips through everywhere
//! else.
//!
//! Layering, lowest to highest precedence:
//! 1. the settings the app saved beside a managed file (`<stem>.local.toml`),
//! 2. the settings file,
//! 3. drop-ins (`<stem>.d/*.toml`, lexicographic order),
//! 4. `KOPUZ_CONFIG_<FIELD>` environment variables.
//!
//! Every layer holds settings only: state, credentials and library data are the DB's ([`is_setting`]).
//!
//! Keys pinned by a layer the settings UI cannot usefully edit — a managed
//! (Nix-store / read-only) file, any drop-in, any env var — are reported in
//! [`FileLayers::locked_keys`] so the UI can gray them out.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use serde_json::Value as JsonValue;
use toml::Value as TomlValue;

/// Env prefix for ad-hoc per-key overrides: `KOPUZ_CONFIG_THEME=nord`,
/// nested fields with `__` (`KOPUZ_CONFIG_EQUALIZER__ENABLED=true`).
pub const ENV_PREFIX: &str = "KOPUZ_CONFIG_";

/// `KOPUZ_CONFIG_PATH` relocates the settings file itself (it is not a field
/// override, so the env layer skips it).
pub const ENV_PATH_OVERRIDE: &str = "KOPUZ_CONFIG_PATH";

const NIX_STORE_PREFIX: &str = "/nix/store";

/// What the app changes by being used rather than through its settings: the DB keeps it, and no settings layer holds it.
pub const STATE_KEYS: &[&str] = &[
    "device_id",
    "active_source",
    "source_explicitly_set",
    "volume",
    "discord_presence_paused",
    "fullscreen_tabs_collapsed",
    "sort_order",
    "album_sort",
    "library_sort",
    "artist_album_sort",
    "artist_sort",
    "album_view_mode",
    "artist_album_view_mode",
    "artists_view_mode",
    "artist_view_order",
    "sidebar_order",
    "home_sections",
    "listen_now_style",
    "hero_height",
];

/// Credentials, which a settings file kept in dotfiles or the Nix store must never hold.
pub const SECRET_KEYS: &[&str] = &[
    "musicbrainz_token",
    "lastfm_api_key",
    "lastfm_api_secret",
    "lastfm_session_key",
    "librefm_api_key",
    "librefm_api_secret",
    "librefm_session_key",
];

/// Library data the DB keeps in its own tables.
pub const DATA_KEYS: &[&str] = &[
    "server",
    "servers",
    "server_folders",
    "listen_counts",
    "offline_tracks",
    "pinned_stations",
    "ytdlp_history",
];

/// Whether a top-level `AppConfig` field is a setting, which only the settings layers hold.
pub fn is_setting(key: &str) -> bool {
    ![STATE_KEYS, SECRET_KEYS, DATA_KEYS]
        .iter()
        .any(|keys| keys.contains(&key))
}

fn settings_only(
    mut map: serde_json::Map<String, JsonValue>,
) -> serde_json::Map<String, JsonValue> {
    map.retain(|key, _| is_setting(key));
    map
}

/// Folds the retired `music_directory` key into the default folder source and makes sure that source exists.
pub(crate) fn fold_legacy_directories(value: &mut JsonValue, force: bool) {
    let Some(obj) = value.as_object_mut() else {
        return;
    };
    let legacy = obj.remove("music_directory").and_then(|raw| match raw {
        JsonValue::String(path) => Some(vec![JsonValue::String(path)]),
        JsonValue::Array(paths) if paths.iter().all(JsonValue::is_string) => Some(paths),
        _ => {
            tracing::warn!("ignoring a music_directory that is neither a path nor a list of paths");
            None
        }
    });
    let sources = obj
        .entry("local_sources")
        .or_insert_with(|| JsonValue::Array(Vec::new()));
    let Some(sources) = sources.as_array_mut() else {
        return;
    };
    let default = sources
        .iter()
        .position(|source| source["id"] == crate::DEFAULT_LOCAL_ID);
    match (default, legacy) {
        (Some(index), Some(dirs)) => {
            let existing = &mut sources[index]["directories"];
            if force || existing.as_array().is_none_or(Vec::is_empty) {
                *existing = JsonValue::Array(dirs);
            }
        }
        (None, dirs) => sources.insert(
            0,
            serde_json::json!({
                "id": crate::DEFAULT_LOCAL_ID,
                "name": crate::DEFAULT_LOCAL_NAME,
                "directories": dirs.unwrap_or_default(),
            }),
        ),
        (Some(_), None) => {}
    }
}

/// The settings file for an app whose database lives in `db_dir`:
/// `KOPUZ_CONFIG_PATH` override, else `<db_dir>/settings.toml` (release) or
/// `settings-debug.toml` (debug builds, mirroring the `kopuz-debug.db` split
/// so `dx serve` never touches real settings).
pub fn settings_path_for(db_dir: &Path) -> PathBuf {
    if let Ok(p) = std::env::var(ENV_PATH_OVERRIDE) {
        return PathBuf::from(p);
    }
    let name = if cfg!(debug_assertions) {
        "settings-debug.toml"
    } else {
        "settings.toml"
    };
    db_dir.join(name)
}

/// The drop-in directory belonging to a settings file: `settings.toml` →
/// `settings.d/` next to it (`settings-debug.toml` → `settings-debug.d/`).
pub fn dropin_dir_for(settings_path: &Path) -> PathBuf {
    let stem = settings_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("settings");
    settings_path.with_file_name(format!("{stem}.d"))
}

/// The writable file beside a managed one, holding the settings it leaves unset: `settings.toml` → `settings.local.toml`.
pub fn local_path_for(settings_path: &Path) -> PathBuf {
    let stem = settings_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("settings");
    settings_path.with_file_name(format!("{stem}.local.toml"))
}

/// The read-side snapshot of every file/env layer, plus what the UI needs to
/// know about mutability.
#[derive(Debug, Clone, Default)]
pub struct FileLayers {
    /// The main settings file this snapshot was read from.
    pub path: PathBuf,
    /// Whether the main file existed at read time.
    pub file_exists: bool,
    /// The main file must not be written: it resolves into the Nix store or is
    /// read-only on disk.
    pub managed: bool,
    /// Top-level `AppConfig` keys pinned by an unwritable layer.
    pub locked_keys: BTreeSet<String>,
    /// Merged overrides (file → drop-ins → env) as a JSON object.
    overrides: JsonValue,
}

impl FileLayers {
    /// Read the file, its drop-ins, and the process environment.
    pub fn read(settings_path: &Path) -> Self {
        Self::read_inner(settings_path, NIX_STORE_PREFIX, std::env::vars())
    }

    fn read_inner(
        settings_path: &Path,
        store_prefix: &str,
        env: impl Iterator<Item = (String, String)>,
    ) -> Self {
        let mut overrides = JsonValue::Object(Default::default());
        let mut locked_keys = BTreeSet::new();

        // Under the main file, so a managed file's keys still win over what the app saved beside it.
        if let Some(map) = read_toml_table(&local_path_for(settings_path)) {
            merge_into(&mut overrides, JsonValue::Object(settings_only(map)));
        }

        let managed = is_managed(settings_path, store_prefix);
        let file_exists;
        if let Some(map) = read_toml_table(settings_path) {
            let map = settings_only(map);
            file_exists = true;
            if managed {
                locked_keys.extend(map.keys().cloned());
            }
            merge_into(&mut overrides, JsonValue::Object(map));
        } else {
            file_exists = settings_path.exists();
        }

        // Drop-ins always lock their keys: they out-rank the main file, so a
        // UI edit saved there could never take effect.
        let dropin_dir = dropin_dir_for(settings_path);
        for path in sorted_toml_files(&dropin_dir) {
            if let Some(map) = read_toml_table(&path) {
                let map = settings_only(map);
                locked_keys.extend(map.keys().cloned());
                merge_into(&mut overrides, JsonValue::Object(map));
            }
        }

        let env_layer = match env_overrides(env) {
            JsonValue::Object(map) => settings_only(map),
            _ => serde_json::Map::new(),
        };
        locked_keys.extend(env_layer.keys().cloned());
        merge_into(&mut overrides, JsonValue::Object(env_layer));

        // The retired key's value now lives in the default folder source.
        if locked_keys.contains("music_directory") {
            locked_keys.insert("local_sources".to_owned());
        }

        Self {
            path: settings_path.to_path_buf(),
            file_exists,
            managed,
            locked_keys,
            overrides,
        }
    }

    /// Whether any layer contributes anything at all.
    pub fn has_overrides(&self) -> bool {
        self.overrides.as_object().is_some_and(|o| !o.is_empty())
    }

    /// Whether the settings UI should treat a top-level config field as
    /// read-only.
    pub fn is_locked(&self, key: &str) -> bool {
        self.locked_keys.contains(key)
    }

    /// Deep-merge the layered overrides over `base` (a config JSON object).
    pub fn apply(&self, base: &mut JsonValue) {
        if self.has_overrides() {
            merge_into(base, self.overrides.clone());
        }
    }

    /// [`apply`](Self::apply) the layers over `base`, then deserialize the
    /// config.
    ///
    /// These files are hand-written and Nix-generated, so a wrong type or a
    /// misspelled enum variant is a normal thing to hit — and one bad key must
    /// not cost the user every other setting. When the merged value doesn't
    /// deserialize, the overridden keys are re-applied one at a time and the
    /// ones that break the parse are dropped with a warning. A `base` that
    /// can't deserialize on its own is still an error: that is the app's own
    /// state, not something a text file caused.
    pub fn merge_and_parse(&self, base: JsonValue) -> Result<crate::AppConfig, serde_json::Error> {
        let mut base = base;
        fold_legacy_directories(&mut base, false);
        let mut merged = base.clone();
        self.apply(&mut merged);
        fold_legacy_directories(&mut merged, true);
        let error = match serde_json::from_value::<crate::AppConfig>(merged) {
            Ok(cfg) => return Ok(cfg),
            Err(error) => error,
        };
        serde_json::from_value::<crate::AppConfig>(base.clone()).map_err(|_| error)?;

        let Some(overrides) = self.overrides.as_object() else {
            return serde_json::from_value(base);
        };
        let mut kept = base;
        let mut dropped: Vec<&str> = Vec::new();
        for (key, value) in overrides {
            let mut candidate = kept.clone();
            merge_into(
                &mut candidate,
                JsonValue::Object(serde_json::Map::from_iter([(key.clone(), value.clone())])),
            );
            fold_legacy_directories(&mut candidate, true);
            if serde_json::from_value::<crate::AppConfig>(candidate.clone()).is_ok() {
                kept = candidate;
            } else {
                dropped.push(key);
            }
        }
        if !dropped.is_empty() {
            tracing::warn!(
                path = %self.path.display(),
                keys = %dropped.join(", "),
                "ignoring unusable config keys from the settings file/drop-ins/env"
            );
        }
        serde_json::from_value(kept)
    }
}

/// Write the settings, only when one changed, to the file or beside a managed one ([`local_path_for`]); answers whether anything was written.
pub fn save_settings_file(
    settings_path: &Path,
    cfg_json: &JsonValue,
    locked_keys: &BTreeSet<String>,
) -> std::io::Result<bool> {
    let written_path = match is_managed(settings_path, NIX_STORE_PREFIX) {
        true => local_path_for(settings_path),
        false => settings_path.to_path_buf(),
    };

    let mut cfg = cfg_json.clone();
    let Some(obj) = cfg.as_object_mut() else {
        return Err(std::io::Error::other(
            "config did not serialize to an object",
        ));
    };
    obj.retain(|key, _| is_setting(key));
    // A pinned key's value in `cfg_json` is the layer's, merged in on load.
    // Writing it back would bake the override into the base file, so it would
    // keep applying once the drop-in/env layer is gone.
    if !locked_keys.is_empty() {
        let existing = read_toml_table(&written_path).unwrap_or_default();
        for key in locked_keys {
            match existing.get(key) {
                Some(value) => obj.insert(key.clone(), value.clone()),
                None => obj.remove(key),
            };
        }
    }
    let table = match json_to_toml(&cfg) {
        Some(TomlValue::Table(table)) => table,
        _ => {
            return Err(std::io::Error::other(
                "config did not serialize to a TOML table",
            ));
        }
    };
    let on_disk = std::fs::read_to_string(&written_path)
        .ok()
        .and_then(|text| text.parse::<toml::Table>().ok());
    if on_disk.as_ref() == Some(&table) {
        return Ok(false);
    }
    let text = toml::to_string_pretty(&table).map_err(std::io::Error::other)?;

    // Follow a writable symlink to its target instead of replacing the link
    // with a regular file. (An hjem-managed link points into the store and
    // never gets here — this is for someone linking the file themselves.)
    let target = std::fs::canonicalize(&written_path).unwrap_or(written_path);
    if let Some(parent) = target.parent()
        && !parent.as_os_str().is_empty()
    {
        std::fs::create_dir_all(parent)?;
    }
    let tmp = target.with_extension("toml.tmp");
    std::fs::write(&tmp, text)?;
    std::fs::rename(&tmp, &target)?;
    Ok(true)
}

/// A file is "managed" when the app must not write it: it is (or resolves
/// through symlinks into) the Nix store, or it exists read-only.
fn is_managed(path: &Path, store_prefix: &str) -> bool {
    if let Ok(target) = std::fs::canonicalize(path)
        && target.starts_with(store_prefix)
    {
        return true;
    }
    match std::fs::metadata(path) {
        Ok(meta) => meta.permissions().readonly(),
        Err(_) => false,
    }
}

fn read_toml_table(path: &Path) -> Option<serde_json::Map<String, JsonValue>> {
    let text = std::fs::read_to_string(path).ok()?;
    match text.parse::<toml::Table>() {
        Ok(table) => match toml_to_json(TomlValue::Table(table)) {
            JsonValue::Object(map) => Some(map),
            _ => None,
        },
        Err(e) => {
            tracing::warn!(path = %path.display(), "ignoring unparsable config layer: {e}");
            None
        }
    }
}

fn sorted_toml_files(dir: &Path) -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut files: Vec<PathBuf> = entries
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "toml") && p.is_file())
        .collect();
    files.sort();
    files
}

/// Build the env layer: every `KOPUZ_CONFIG_<FIELD>` (except the path
/// override) becomes a lowercased field, `__` separating nested objects. The
/// value is parsed as a TOML value (`true`, `3`, `["a"]`, …), else taken as a
/// plain string.
fn env_overrides(env: impl Iterator<Item = (String, String)>) -> JsonValue {
    let mut layer = JsonValue::Object(Default::default());
    let mut vars: Vec<(String, String)> = env
        .filter(|(k, _)| k.starts_with(ENV_PREFIX) && k != ENV_PATH_OVERRIDE)
        .collect();
    vars.sort();
    for (key, raw) in vars {
        let path: Vec<String> = key[ENV_PREFIX.len()..]
            .split("__")
            .map(|s| s.to_lowercase())
            .filter(|s| !s.is_empty())
            .collect();
        if path.is_empty() {
            continue;
        }
        let value = parse_env_value(&raw);
        let mut nested = value;
        for part in path.iter().rev() {
            let mut obj = serde_json::Map::new();
            obj.insert(part.clone(), nested);
            nested = JsonValue::Object(obj);
        }
        merge_into(&mut layer, nested);
    }
    layer
}

/// Parse one env value as the right-hand side of a TOML assignment, so
/// `5`/`true`/`["a"]`/`"quoted"` keep their types and anything else (`nord`)
/// stays a bare string.
fn parse_env_value(raw: &str) -> JsonValue {
    format!("v = {raw}")
        .parse::<toml::Table>()
        .ok()
        .and_then(|mut t| t.remove("v"))
        .map(toml_to_json)
        .unwrap_or_else(|| JsonValue::String(raw.to_string()))
}

fn toml_to_json(value: TomlValue) -> JsonValue {
    match value {
        TomlValue::String(s) => JsonValue::String(s),
        TomlValue::Integer(i) => JsonValue::Number(i.into()),
        TomlValue::Float(f) => serde_json::Number::from_f64(f)
            .map(JsonValue::Number)
            .unwrap_or(JsonValue::Null),
        TomlValue::Boolean(b) => JsonValue::Bool(b),
        // No config field is a date; keep the text so it at least deserializes
        // into a string field instead of vanishing.
        TomlValue::Datetime(dt) => JsonValue::String(dt.to_string()),
        TomlValue::Array(items) => JsonValue::Array(items.into_iter().map(toml_to_json).collect()),
        TomlValue::Table(table) => JsonValue::Object(
            table
                .into_iter()
                .map(|(k, v)| (k, toml_to_json(v)))
                .collect(),
        ),
    }
}

/// TOML has no null: `None` fields are dropped, which is exactly right for
/// `AppConfig` (every field is `#[serde(default)]`, so an absent key restores
/// the default).
fn json_to_toml(value: &JsonValue) -> Option<TomlValue> {
    Some(match value {
        JsonValue::Null => return None,
        JsonValue::Bool(b) => TomlValue::Boolean(*b),
        JsonValue::Number(n) => match (n.as_i64(), n.as_f64()) {
            (Some(i), _) => TomlValue::Integer(i),
            (None, Some(f)) if f.is_finite() => TomlValue::Float(shorten_f32(f)),
            _ => return None,
        },
        JsonValue::String(s) => TomlValue::String(s.clone()),
        JsonValue::Array(items) => {
            TomlValue::Array(items.iter().filter_map(json_to_toml).collect())
        }
        JsonValue::Object(map) => TomlValue::Table(
            map.iter()
                .filter_map(|(k, v)| Some((k.clone(), json_to_toml(v)?)))
                .collect(),
        ),
    })
}

/// `serde_json` widens the config's `f32` fields to `f64`, so `volume = 0.05`
/// would land in the file as `0.05000000074505806`. A value that survives a
/// round trip through `f32` came from one, so write the short form a human
/// would have typed; anything genuinely `f64` keeps full precision.
fn shorten_f32(f: f64) -> f64 {
    let narrow = f as f32;
    if f64::from(narrow) != f {
        return f;
    }
    format!("{narrow}").parse().unwrap_or(f)
}

/// Deep merge: objects merge key-wise, everything else replaces.
fn merge_into(base: &mut JsonValue, layer: JsonValue) {
    match (base, layer) {
        (JsonValue::Object(base_map), JsonValue::Object(layer_map)) => {
            for (key, value) in layer_map {
                match base_map.get_mut(&key) {
                    Some(slot) if slot.is_object() && value.is_object() => {
                        merge_into(slot, value);
                    }
                    _ => {
                        base_map.insert(key, value);
                    }
                }
            }
        }
        (base, layer) => *base = layer,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::AppConfig;

    fn empty_env() -> impl Iterator<Item = (String, String)> {
        std::iter::empty()
    }

    fn default_dirs(cfg: &AppConfig) -> Vec<PathBuf> {
        cfg.local_sources
            .iter()
            .find(|source| source.id == crate::DEFAULT_LOCAL_ID)
            .map(|source| source.directories.clone())
            .unwrap_or_default()
    }

    fn no_layers() -> FileLayers {
        let dir = tempfile::tempdir().unwrap();
        FileLayers::read_inner(&dir.path().join("none.toml"), NIX_STORE_PREFIX, empty_env())
    }

    #[test]
    fn a_stored_music_directory_becomes_the_default_folder_source() {
        for (stored, want) in [
            (serde_json::json!("/music"), vec!["/music"]),
            (
                serde_json::json!(["/music", "/archive"]),
                vec!["/music", "/archive"],
            ),
            (serde_json::json!([]), vec![]),
        ] {
            let cfg = no_layers()
                .merge_and_parse(serde_json::json!({ "music_directory": stored }))
                .unwrap();
            assert_eq!(
                default_dirs(&cfg),
                want.iter().map(PathBuf::from).collect::<Vec<_>>()
            );
            assert_eq!(cfg.local_sources[0].id, crate::DEFAULT_LOCAL_ID);
        }
    }

    #[test]
    fn the_default_folder_source_exists_even_when_nothing_was_stored() {
        let cfg = no_layers().merge_and_parse(serde_json::json!({})).unwrap();
        assert_eq!(cfg.local_sources.len(), 1);
        assert!(default_dirs(&cfg).is_empty());
        assert_eq!(cfg.active_source.as_str(), "local");
    }

    #[test]
    fn a_migrated_source_is_not_overwritten_by_a_leftover_key() {
        let cfg = no_layers()
            .merge_and_parse(serde_json::json!({
                "music_directory": ["/old"],
                "local_sources": [
                    {"id": "local:x", "name": "X", "directories": ["/x"]},
                    {"id": "local", "name": "Local Library", "directories": ["/new"]},
                ],
            }))
            .unwrap();
        assert_eq!(default_dirs(&cfg), vec![PathBuf::from("/new")]);
        assert_eq!(cfg.local_sources.len(), 2);
    }

    #[test]
    fn a_managed_file_with_music_directory_wins_and_locks_the_folder_sources() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        std::fs::write(&path, "music_directory = [\"/nix/music\"]\n").unwrap();
        let mut perms = std::fs::metadata(&path).unwrap().permissions();
        perms.set_readonly(true);
        std::fs::set_permissions(&path, perms).unwrap();

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        assert!(layers.managed);
        assert!(layers.is_locked("local_sources"));

        let blob = serde_json::json!({
            "local_sources": [{"id": "local", "name": "Local Library", "directories": ["/db"]}],
        });
        let cfg = layers.merge_and_parse(blob).unwrap();
        assert_eq!(default_dirs(&cfg), vec![PathBuf::from("/nix/music")]);
    }

    #[test]
    fn a_managed_empty_music_directory_clears_the_default_folder_source() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        std::fs::write(&path, "music_directory = []\n").unwrap();
        let mut perms = std::fs::metadata(&path).unwrap().permissions();
        perms.set_readonly(true);
        std::fs::set_permissions(&path, perms).unwrap();

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        let blob = serde_json::json!({
            "local_sources": [{"id": "local", "name": "Local Library", "directories": ["/db"]}],
        });
        let cfg = layers.merge_and_parse(blob).unwrap();
        assert!(default_dirs(&cfg).is_empty());
    }

    #[test]
    fn a_malformed_music_directory_is_dropped_not_fatal() {
        let cfg = no_layers()
            .merge_and_parse(serde_json::json!({ "music_directory": 7 }))
            .unwrap();
        assert!(default_dirs(&cfg).is_empty());
    }

    #[test]
    fn every_stored_active_source_spelling_still_loads() {
        for (stored, column) in [
            (serde_json::json!("Local"), "local"),
            (
                serde_json::json!({"LocalLibrary": "local:abc"}),
                "local:abc",
            ),
            (serde_json::json!({"Server": "srv"}), "srv"),
        ] {
            let source: crate::Source = serde_json::from_value(stored.clone()).unwrap();
            assert_eq!(source.as_str(), column);
            assert_eq!(serde_json::to_value(&source).unwrap(), stored);
            assert_eq!(crate::Source::from_column(column), source);
        }
    }

    #[test]
    fn material_style_and_system_colors_survive_a_settings_reload() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        let cfg = AppConfig {
            ui_style: crate::UiStyle::Material3,
            theme: "system".into(),
            ..Default::default()
        };
        save_settings_file(&path, &serde_json::to_value(cfg).unwrap(), &BTreeSet::new()).unwrap();
        let restored = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env())
            .merge_and_parse(serde_json::json!({}))
            .unwrap();
        assert_eq!(restored.ui_style, crate::UiStyle::Material3);
        assert_eq!(restored.theme, "system");
    }

    #[test]
    fn default_config_round_trips_through_the_settings_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        let cfg_json = serde_json::to_value(AppConfig::default()).unwrap();

        assert!(save_settings_file(&path, &cfg_json, &BTreeSet::new()).unwrap());

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        let mut base = serde_json::json!({});
        layers.apply(&mut base);
        let restored: AppConfig = serde_json::from_value(base).unwrap();

        let defaults = AppConfig::default();
        assert_eq!(restored.theme, defaults.theme);
        assert_eq!(restored.local_sources, defaults.local_sources);
        assert_eq!(restored.volume, defaults.volume);
        assert_eq!(restored.home_sections, defaults.home_sections);
        assert_eq!(restored.equalizer, defaults.equalizer);
        assert_eq!(restored.radio_registries, defaults.radio_registries);
        assert_eq!(restored.sidebar_order, defaults.sidebar_order);
        assert_eq!(restored.downloader_options, defaults.downloader_options);
    }

    /// Every collection/enum/nested shape at once: the default config is
    /// mostly empty vectors and unit enums, so it would not catch a field that
    /// TOML can't express (array of tables, map of maps, fixed-size float
    /// array) or one whose key ordering breaks the writer.
    #[test]
    fn a_fully_populated_config_round_trips_through_the_settings_file() {
        use std::collections::HashMap;

        use crate::{
            AlbumSortField, AlbumViewMode, BackBehavior, ChannelMode, CustomTheme,
            DeviceChangeBehavior, EqPreset, EqualizerSettings, FetchStrategy, HomeSection,
            ListenNowStyle, OfflineQuality, PlayerBarPosition, RegistryEntry, SampleRateMode,
            SavedLocalSource, SettingsLayout, SortCriterion, SortDirection, SortOrder,
            TitlebarMode, UiStyle,
        };

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        let cfg = AppConfig {
            local_sources: vec![
                SavedLocalSource {
                    id: "local:one".into(),
                    name: "Archive".into(),
                    directories: vec!["/music/a".into(), "/music/b".into()],
                },
                SavedLocalSource {
                    id: "local:two".into(),
                    name: "Field recordings".into(),
                    directories: vec![],
                },
            ],
            active_source: crate::Source::LocalLibrary("local:two".into()),
            spotify_browser: Some("brave".into()),
            spotify_prefer_active_device: false,
            theme: "custom-one".into(),
            discord_presence: Some(false),
            discord_presence_paused: None,
            sort_order: SortOrder::Album,
            album_sort: vec![
                SortCriterion::new(AlbumSortField::Year, SortDirection::Desc),
                SortCriterion::new(AlbumSortField::Title, SortDirection::Asc),
            ],
            album_view_mode: AlbumViewMode::List,
            language: "tr".into(),
            cover_art_darkening: 42,
            custom_font_path: "/fonts/Inter.ttf".into(),
            sidebar_order: vec!["home".into(), "albums".into()],
            volume: 0.33,
            crossfade_seconds: 7,
            custom_themes: HashMap::from([(
                "custom-one".to_string(),
                CustomTheme {
                    name: "Custom One".into(),
                    vars: HashMap::from([
                        ("--color-bg".to_string(), "#101010".to_string()),
                        ("--color-fg".to_string(), "#eeeeee".to_string()),
                    ]),
                },
            )]),
            back_behavior: BackBehavior::AlwaysPrev,
            channel_mode: ChannelMode::Mono,
            equalizer: EqualizerSettings {
                enabled: true,
                preset: EqPreset::Custom,
                bands: [-6.0, -3.5, 0.0, 1.5, 3.0, 4.5, 6.0, -1.0, -2.0, 12.0],
                preamp_db: -2.5,
            },
            device_change_behavior: DeviceChangeBehavior::Resume,
            sample_rate_mode: SampleRateMode::Source,
            downloader_output_dir: "/downloads".into(),
            titlebar_mode: TitlebarMode::System,
            offline_quality: OfflineQuality::Original,
            player_bar_position: PlayerBarPosition::Top,
            ui_style: UiStyle::Vaxry,
            settings_layout: SettingsLayout::TopBar,
            hero_height: 420,
            home_sections: vec![
                HomeSection {
                    key: "recently_played".into(),
                    enabled: false,
                },
                HomeSection {
                    key: "favorites".into(),
                    enabled: true,
                },
            ],
            listen_now_style: ListenNowStyle::Cards,
            auto_fetch_covers: true,
            cover_fetch_strategy: FetchStrategy::LastFmOnly,
            radio_registries: vec![RegistryEntry {
                url: "https://example.invalid/index.json".into(),
                enabled: false,
                is_default: false,
            }],
            pinned_stations: vec!["https://example.invalid/station.json".into()],
            prefer_local_lyrics: true,
            ..Default::default()
        };

        let written = save_settings_file(
            &path,
            &serde_json::to_value(&cfg).unwrap(),
            &BTreeSet::new(),
        );
        assert!(written.unwrap(), "settings file not written");

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        let mut base = serde_json::json!({});
        layers.apply(&mut base);
        let restored: AppConfig = serde_json::from_value(base).unwrap();

        assert_eq!(restored.local_sources, cfg.local_sources);
        assert_eq!(restored.spotify_browser, cfg.spotify_browser);
        assert_eq!(
            restored.spotify_prefer_active_device,
            cfg.spotify_prefer_active_device
        );
        assert_eq!(restored.theme, cfg.theme);
        assert_eq!(restored.discord_presence, cfg.discord_presence);
        assert_eq!(restored.language, cfg.language);
        assert_eq!(restored.cover_art_darkening, cfg.cover_art_darkening);
        assert_eq!(restored.custom_font_path, cfg.custom_font_path);
        assert_eq!(restored.crossfade_seconds, cfg.crossfade_seconds);
        assert_eq!(
            serde_json::to_value(&restored.custom_themes).unwrap(),
            serde_json::to_value(&cfg.custom_themes).unwrap()
        );
        assert_eq!(restored.back_behavior, cfg.back_behavior);
        assert_eq!(restored.channel_mode, cfg.channel_mode);
        assert_eq!(restored.equalizer, cfg.equalizer);
        assert_eq!(restored.device_change_behavior, cfg.device_change_behavior);
        assert_eq!(restored.sample_rate_mode, cfg.sample_rate_mode);
        assert_eq!(restored.downloader_output_dir, cfg.downloader_output_dir);
        assert_eq!(restored.titlebar_mode, cfg.titlebar_mode);
        assert_eq!(restored.offline_quality, cfg.offline_quality);
        assert_eq!(restored.player_bar_position, cfg.player_bar_position);
        assert_eq!(restored.ui_style, cfg.ui_style);
        assert_eq!(restored.settings_layout, cfg.settings_layout);
        assert_eq!(restored.auto_fetch_covers, cfg.auto_fetch_covers);
        assert_eq!(restored.cover_fetch_strategy, cfg.cover_fetch_strategy);
        assert_eq!(restored.radio_registries, cfg.radio_registries);
        assert_eq!(restored.prefer_local_lyrics, cfg.prefer_local_lyrics);

        assert_eq!(
            restored.volume,
            AppConfig::default().volume,
            "state stays in the DB"
        );
    }

    #[test]
    fn f32_fields_are_written_short_and_reload_identically() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        let cfg = AppConfig {
            volume_scroll_step: 0.05,
            ..Default::default()
        };

        save_settings_file(
            &path,
            &serde_json::to_value(&cfg).unwrap(),
            &BTreeSet::new(),
        )
        .unwrap();

        let text = std::fs::read_to_string(&path).unwrap();
        assert!(
            text.contains("volume_scroll_step = 0.05\n"),
            "f32 widening leaked into the file:\n{text}"
        );

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        let mut base = serde_json::json!({});
        layers.apply(&mut base);
        let restored: AppConfig = serde_json::from_value(base).unwrap();
        assert_eq!(restored.volume_scroll_step, cfg.volume_scroll_step);
    }

    #[test]
    fn nothing_but_settings_reaches_or_leaves_a_settings_layer() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        let mut cfg = AppConfig::default();
        cfg.offline_tracks
            .insert("track".into(), "/tmp/x.mp3".into());
        cfg.lastfm_session_key = "secret".into();
        cfg.volume = 0.2;
        let cfg_json = serde_json::to_value(&cfg).unwrap();

        save_settings_file(&path, &cfg_json, &BTreeSet::new()).unwrap();

        let written: toml::Table = std::fs::read_to_string(&path).unwrap().parse().unwrap();
        for key in [STATE_KEYS, SECRET_KEYS, DATA_KEYS].concat() {
            assert!(!written.contains_key(key), "{key} leaked into the file");
        }

        // A file an older build wrote still holds them; no layer may hand them back.
        std::fs::write(
            &path,
            "volume = 0.9\nlastfm_session_key = \"old\"\ntheme = \"nord\"\n",
        )
        .unwrap();
        let env = [("KOPUZ_CONFIG_VOLUME".to_string(), "0.1".to_string())].into_iter();
        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, env);
        let mut base = serde_json::json!({});
        layers.apply(&mut base);
        assert_eq!(base, serde_json::json!({ "theme": "nord" }));
        assert!(!layers.is_locked("volume"));
    }

    #[test]
    fn dropins_and_env_out_rank_the_file_and_lock_their_keys() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        std::fs::write(&path, "theme = \"nord\"\nlanguage = \"de\"\n").unwrap();
        let dropin_dir = dropin_dir_for(&path);
        std::fs::create_dir_all(&dropin_dir).unwrap();
        std::fs::write(dropin_dir.join("10-theme.toml"), "theme = \"dracula\"\n").unwrap();
        let env = vec![("KOPUZ_CONFIG_THEME".to_string(), "gruvbox".to_string())];

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, env.into_iter());

        let mut base = serde_json::json!({ "theme": "default", "volume": 0.5 });
        layers.apply(&mut base);
        assert_eq!(base["theme"], "gruvbox");
        assert_eq!(base["language"], "de");
        assert_eq!(base["volume"], 0.5);
        // A writable main file doesn't lock; drop-ins and env do.
        assert!(layers.is_locked("theme"));
        assert!(!layers.is_locked("language"));
        assert!(!layers.managed);
    }

    #[test]
    fn nested_toml_tables_merge_key_wise() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        std::fs::write(
            &path,
            "[equalizer]\nenabled = true\npreamp_db = -3.0\npreset = \"Custom\"\n",
        )
        .unwrap();

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        let mut base = serde_json::json!({ "equalizer": { "enabled": false, "bands": [1.0] } });
        layers.apply(&mut base);

        assert_eq!(base["equalizer"]["enabled"], true);
        assert_eq!(base["equalizer"]["preamp_db"], -3.0);
        // Untouched sub-keys survive the merge.
        assert_eq!(base["equalizer"]["bands"], serde_json::json!([1.0]));
    }

    #[test]
    fn env_values_parse_as_toml_with_string_fallback() {
        let env = vec![
            (
                "KOPUZ_CONFIG_CROSSFADE_SECONDS".to_string(),
                "5".to_string(),
            ),
            ("KOPUZ_CONFIG_THEME".to_string(), "nord".to_string()),
            (
                "KOPUZ_CONFIG_EQUALIZER__ENABLED".to_string(),
                "true".to_string(),
            ),
            (
                "KOPUZ_CONFIG_MUSIC_DIRECTORY".to_string(),
                r#"["/music", "/archive"]"#.to_string(),
            ),
            ("KOPUZ_CONFIG_PATH".to_string(), "/tmp/x.toml".to_string()),
        ];
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, env.into_iter());

        let mut base = serde_json::json!({});
        layers.apply(&mut base);
        assert_eq!(base["crossfade_seconds"], 5);
        assert_eq!(base["theme"], "nord");
        assert_eq!(base["equalizer"]["enabled"], true);
        assert_eq!(base["music_directory"][1], "/archive");
        // The path override is not a field.
        assert!(base.get("path").is_none());
        assert!(layers.is_locked("equalizer"));
    }

    #[test]
    fn a_managed_file_is_never_written_and_the_rest_goes_beside_it() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        std::fs::write(&path, "theme = \"nord\"\n").unwrap();
        let mut perms = std::fs::metadata(&path).unwrap().permissions();
        perms.set_readonly(true);
        std::fs::set_permissions(&path, perms).unwrap();

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        assert!(layers.managed);
        assert!(layers.is_locked("theme"));

        let cfg = AppConfig {
            theme: "nord".into(),
            language: "tr".into(),
            ..Default::default()
        };
        let cfg_json = serde_json::to_value(&cfg).unwrap();
        assert!(save_settings_file(&path, &cfg_json, &layers.locked_keys).unwrap());

        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            "theme = \"nord\"\n"
        );
        let local: toml::Table = std::fs::read_to_string(local_path_for(&path))
            .unwrap()
            .parse()
            .unwrap();
        assert!(
            !local.contains_key("theme"),
            "the managed key stays the managed file's"
        );
        assert_eq!(local.get("language").and_then(|v| v.as_str()), Some("tr"));

        std::fs::write(
            local_path_for(&path),
            "theme = \"gruvbox\"\nlanguage = \"tr\"\n",
        )
        .unwrap();
        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        let restored = layers.merge_and_parse(serde_json::json!({})).unwrap();
        assert_eq!(
            (restored.theme.as_str(), restored.language.as_str()),
            ("nord", "tr")
        );
    }

    #[test]
    fn a_save_that_changes_no_setting_leaves_the_file_as_written() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        let mut cfg = AppConfig::default();
        let cfg_json = serde_json::to_value(&cfg).unwrap();
        save_settings_file(&path, &cfg_json, &BTreeSet::new()).unwrap();
        let hand_written = format!("# mine\n{}", std::fs::read_to_string(&path).unwrap());
        std::fs::write(&path, &hand_written).unwrap();

        cfg.volume = 0.5;
        let saved = save_settings_file(
            &path,
            &serde_json::to_value(&cfg).unwrap(),
            &BTreeSet::new(),
        );

        assert!(!saved.unwrap(), "only state changed");
        assert_eq!(std::fs::read_to_string(&path).unwrap(), hand_written);
    }

    #[cfg(unix)]
    #[test]
    fn symlink_into_store_prefix_is_managed() {
        let dir = tempfile::tempdir().unwrap();
        let store = dir.path().join("nix-store");
        std::fs::create_dir_all(&store).unwrap();
        let target = store.join("abc-kopuz-settings.toml");
        std::fs::write(&target, "theme = \"nord\"\n").unwrap();
        let link = dir.path().join("settings.toml");
        std::os::unix::fs::symlink(&target, &link).unwrap();

        let layers = FileLayers::read_inner(&link, store.to_str().unwrap(), empty_env());

        assert!(layers.managed);
        assert!(layers.is_locked("theme"));
    }

    /// A hand-made link to a writable file: the write lands on the target and
    /// the link survives.
    #[cfg(unix)]
    #[test]
    fn writable_symlink_is_written_through_not_replaced() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("dotfiles-settings.toml");
        std::fs::write(&target, "theme = \"nord\"\n").unwrap();
        let link = dir.path().join("settings.toml");
        std::os::unix::fs::symlink(&target, &link).unwrap();

        let cfg_json = serde_json::to_value(AppConfig::default()).unwrap();
        assert!(save_settings_file(&link, &cfg_json, &BTreeSet::new()).unwrap());

        assert!(std::fs::symlink_metadata(&link).unwrap().is_symlink());
        let written: toml::Table = std::fs::read_to_string(&target).unwrap().parse().unwrap();
        assert_eq!(written["theme"].as_str(), Some("default"));
    }

    /// The exact snippet the README hands to hjem users. If a rename ever makes
    /// it stale, this fails instead of the user's first launch.
    #[test]
    fn the_documented_hjem_example_deserializes() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        std::fs::write(
            &path,
            "theme = \"gruvbox\"\nlanguage = \"en\"\ncrossfade_seconds = 3\n\n[equalizer]\nenabled = true\n",
        )
        .unwrap();

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        let cfg = layers.merge_and_parse(serde_json::json!({})).unwrap();

        assert_eq!(cfg.theme, "gruvbox");
        assert_eq!(cfg.language, "en");
        assert_eq!(cfg.crossfade_seconds, 3);
        assert!(cfg.equalizer.enabled);
        // Only `enabled` was set, so the rest of the table keeps its defaults.
        assert_eq!(cfg.equalizer.bands, AppConfig::default().equalizer.bands);
    }

    #[test]
    fn one_unusable_key_is_dropped_instead_of_failing_the_whole_config() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        std::fs::write(
            &path,
            // `crossfade_seconds` wants an integer and `ui_style` a known
            // variant — the two ways a hand-written value goes wrong.
            "theme = \"nord\"\ncrossfade_seconds = \"loud\"\nui_style = \"Fancy\"\nlanguage = \"tr\"\n",
        )
        .unwrap();

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        let base = serde_json::json!({ "theme": "default", "crossfade_seconds": 3 });
        let cfg = layers.merge_and_parse(base).expect("config still loads");

        assert_eq!(cfg.theme, "nord", "good keys still apply");
        assert_eq!(cfg.language, "tr");
        assert_eq!(cfg.crossfade_seconds, 3, "the base value survives");
        assert_eq!(cfg.ui_style, crate::UiStyle::default());
    }

    #[test]
    fn a_broken_base_is_still_an_error() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        std::fs::write(&path, "theme = \"nord\"\n").unwrap();

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        let base = serde_json::json!({ "volume": { "not": "a number" } });

        assert!(
            layers.merge_and_parse(base).is_err(),
            "a corrupt blob must not be papered over — saves stay disabled"
        );
    }

    #[test]
    fn missing_file_has_no_overrides_and_is_not_managed() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());

        assert!(!layers.has_overrides());
        assert!(!layers.managed);
        assert!(!layers.file_exists);
        assert!(layers.locked_keys.is_empty());
    }

    #[test]
    fn unparsable_file_is_ignored_rather_than_fatal() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        std::fs::write(&path, "this is not = = toml\n").unwrap();

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());

        assert!(!layers.has_overrides());
        assert!(layers.file_exists);
    }
}
